# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bce7778521a9554f9675e4a92742b7a7f774d1d1443a393a871bb58ea826da84b4196c4c38717a0b1a0d21e6d795d921f106625b6d746d8d5eca524e8a91b38a

test:
  secret_key_base: 24cce60585e6d2275cd39c3a947a3387b7a80643e054bb2ccde5ee29d8827c5816b96e29c362507f9e97a247351989e4e91ec78a4a144170ab14e883cc942d59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
